### ISSUE TITLE
장학금/지원금 페이지 API 연결

### ISSUE THREAD

**Issue by EnoughKK** [EnoughKK/UMC_badjang_Android#15]
## To-do
- [x] 장학금 조회 API 연결
- [x]  지원금 조회 API 연결
- [ ] 장학금/지원금 필터 API 연결

## #✔️기타사항
